// Package models provides forecasting model interfaces and implementations for Kedastral.
//
// Models consume historical metric data in the form of FeatureFrames and produce
// Forecasts representing predicted future values over a specified horizon.
// The baseline model implementation uses exponential moving averages and optional
// seasonality patterns for prediction.
package models

import (
	"context"
)

// FeatureFrame represents a collection of feature rows for model training and prediction.
// Each row is a map of feature names to their float64 values, typically including
// timestamps and derived features like hour-of-day or day-of-week.
//
// Example:
//
//	FeatureFrame{
//	    Rows: []map[string]float64{
//	        {"timestamp": 1609459200, "value": 150.0, "hour": 0, "day": 5},
//	        {"timestamp": 1609459260, "value": 155.0, "hour": 0, "day": 5},
//	    },
//	}
type FeatureFrame struct {
	Rows []map[string]float64
}

// Forecast represents a time-series forecast generated by a model.
// Values contains the predicted metric values at regular intervals (StepSec)
// over the forecast horizon (Horizon seconds).
//
// The length of Values should be: len(Values) = Horizon / StepSec
//
// Models may optionally provide quantile predictions (Quantiles) to represent
// forecast uncertainty. When quantiles are available, the capacity planner
// can use them directly instead of applying a headroom multiplier.
type Forecast struct {
	// Metric is the name of the metric being forecast (e.g., "http_rps")
	Metric string

	// Values contains the forecast predictions at regular intervals (point estimate)
	Values []float64

	// StepSec is the interval in seconds between consecutive values
	StepSec int

	// Horizon is the total forecast window in seconds
	Horizon int

	// Quantiles contains optional quantile predictions for uncertainty estimation.
	// Keys are quantile levels (e.g., 0.5, 0.75, 0.9, 0.95).
	// Each value is a slice of predictions matching the length of Values.
	// If nil or empty, the capacity planner falls back to using headroom.
	//
	// Example:
	//   Quantiles: map[float64][]float64{
	//     0.50: []float64{100, 105, 110},  // median (same as Values)
	//     0.90: []float64{120, 126, 132},  // 90th percentile
	//     0.95: []float64{130, 137, 144},  // 95th percentile
	//   }
	Quantiles map[float64][]float64
}

// Model defines the interface for forecasting models.
// Implementations must be safe for concurrent use if documented as such.
//
// The baseline implementation (baseline.go) provides a simple moving average
// with optional seasonality that requires no training.
type Model interface {
	// Train trains the model on historical data.
	// For stateless models like baseline, this may be a no-op.
	// Returns an error if training fails or if the history is insufficient.
	//
	// The context can be used to cancel long-running training operations.
	Train(ctx context.Context, history FeatureFrame) error

	// Predict generates a forecast based on the provided features.
	// The features typically include recent historical values and time-based
	// features (hour, day, etc.) extracted from the data.
	//
	// Returns an error if prediction fails or if features are invalid.
	// The returned Forecast must have non-negative values.
	Predict(ctx context.Context, features FeatureFrame) (Forecast, error)

	// Name returns the model's identifier (e.g., "baseline", "arima").
	// Used for logging, metrics, and model selection.
	Name() string
}
